import type { CheckResult, Report, Status } from '../types.js';

const STATUS_EMOJI: Record<Status, string> = {
  pass: '✅',
  fail: '❌',
  warn: '⚠️',
  skip: '➖',
};

/**
 * Render the report as GitHub-flavored Markdown.
 *
 * Designed to be posted as a PR comment by the bundled GitHub Action — the
 * structure stays compact and readable even when collapsed by reviewers.
 */
export function renderMarkdown(report: Report): string {
  const lines: string[] = [];
  lines.push(`# 🩺 Repo Vitals Report`);
  lines.push('');
  lines.push(`**Overall Score:** \`${report.score}/100\`  •  **Grade:** \`${report.grade}\``);
  lines.push('');
  if (report.language) {
    lines.push(`_Detected language: ${report.language}_`);
    lines.push('');
  }
  for (const cat of report.categories) {
    lines.push(`## ${cat.title} (${cat.score}/${cat.maxScore})`);
    lines.push('');
    lines.push('| Status | Check | Points | Message |');
    lines.push('| :---: | :--- | :---: | :--- |');
    for (const c of cat.checks) {
      lines.push(rowFor(c));
    }
    lines.push('');
  }
  if (report.topSuggestions.length) {
    lines.push('## Top suggestions');
    lines.push('');
    report.topSuggestions.forEach((s, i) => {
      lines.push(`${i + 1}. ${s}`);
    });
    lines.push('');
  }
  lines.push('---');
  lines.push(
    `<sub>Generated by [repo-vitals](https://github.com/ikereliasvivar2026-pixel/repo-vitals) v${report.version}</sub>`,
  );
  return lines.join('\n');
}

function rowFor(c: CheckResult): string {
  const emoji = STATUS_EMOJI[c.status];
  return `| ${emoji} | ${escapePipes(c.title)} | ${c.earned}/${c.weight} | ${escapePipes(c.message)} |`;
}

/**
 * Escape a check message so it remains a single, well-formed markdown table
 * cell. We escape backslashes first (so subsequent escapes are not themselves
 * re-escaped), then pipes (which would otherwise terminate the cell), then
 * collapse any embedded newlines into spaces.
 */
function escapePipes(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}
